language: python
python:
- '3.6'
sudo: required
dist: trusty
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
- export python_version=$TRAVIS_PYTHON_VERSION
- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create --name workqueue
- source activate workqueue
- pip install -r requirements.txt
- python manage.py migrate
script:
- python manage.py runserver &
- python manage.py test
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
