# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='status',
            field=models.CharField(default='COMPLETE', max_length=200),
            preserve_default=False,
        ),
    ]
