# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0004_workunit_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='logs',
            field=models.TextField(null=True),
        ),
    ]
